### ISSUE TITLE
Add calendar component

### ISSUE THREAD

**Issue by rlafuente** [faktenforum/faktenforum-frontend#21]
We need a calendar view like [StartHub](https://correctiv.org/projekte/correctiv-starthub/)'s, that draws its content from a Google Sheet.

There's now a [branch](https://github.com/faktenforum/faktenforum-frontend/tree/21-calendar) with a minimal implementation, several caveats:

- written in vanilla JS using Axios, not TypeScript
- not using any library for Google APIs, just GETting the base json through http
- it should use v-list like the previous mock component, but I couldn't get it to work so I went with a div with v-for
- i'm sure there's lots of details missing to play nice with the rest of the application, but I'm pushing this as a barebones implementation that we can finesse as we go

**Comment by likt0r** [comment]
HI Ricardo,
it looks good as baseline we can improve on.
I would recommend to use [$fetch ](https://nuxt.com/docs/api/utils/dollarfetch) instead of axios, it is already included in nuxt, so we do not need another lib.
If we do not need a google lib for fetching the data even better :)
What was the problem with v-list ?

Can you exchange axios with $fetch, or should I take from here ?

A small hint you can create or attach a branch to an issue on the right side. 

Greetings

**Comment by rlafuente** [comment]
Hi!

I can swap axios for $fetch no problem, but only next Tuesday. Feel free to jump in if you want to wrap this one up.

About v-list, I don't remember the exact error but I struggled to understand how it worked. I didn't read up much since I could just use v-for and be done with it for a first implementation. But I could also look into that next Tuesday.

And thank you for the branch/issue tip, I had no idea :-)
