### ISSUE TITLE
Update Calendar Component to Typescript and Google Calendar

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum-frontend#50]
```[tasklist]
### Tasks
- [x] Update to Typescript
- [x] Get data from google calendar
```

**Comment by likt0r** [comment]
CalenderURL: https://calendar.google.com/calendar/u/0?cid=MGRiMzVhNjhjMjAzMmE2YWY2NTRhMDE5ZDQxOTY4N2EwYjY4YzJiMTU1OTFlNjM3MTI4NTQ4ZWM3MTBjZDJlMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

Data should be fetched by nuxt backend and provided by a route (f.e: server/api/events.get.ts)

**Comment by stephanmax** [comment]
@CaLi-Correctiv: There are a couple of minor points that we need to consider after switching from [Google Sheets](https://docs.google.com/spreadsheets/d/1LMXBxJ9tE4fwL3Fj9yJ5xf2g6u7lr0h7A0HDVpP7g3A/edit) to [Google Calendar](https://calendar.google.com/calendar/u/0?cid=MGRiMzVhNjhjMjAzMmE2YWY2NTRhMDE5ZDQxOTY4N2EwYjY4YzJiMTU1OTFlNjM3MTI4NTQ4ZWM3MTBjZDJlMUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) as the source for our events:

* Google Calendar does not have dedicated input fields for `url` and `link_text`, instead this kind of information can be included in the general description of the calendar entry. Let me know if that works for all cases.
* Should we output the `LOCATION` field (e.g. Zoom link) if present?
* Since events are not manually curated inside the Google Sheet anymore, what is the threshold of ignoring past events, i.e. after how many days should they disappear from the landing page?
* Descending sort by event date still okay?

**Comment by CaLi-Correctiv** [comment]
@stephanmax thanks!
- Can we work with deep-links within the general description? If yes, that will do. 
- Concerning Location field, yes, could be useful to add it. However, it should be short and like "Zoom" and not the full link. 
- I'd say they can disappear the day after or a couple of days after the actual happening. 
- Yes, sorting them by date is fine.
